### ISSUE TITLE
Versioning Artifacts

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/Diagnoser#3]
Hello all,

Regarding versioning artifacts to run experiments, as I understood, I should do the followings:
1. Keep hashes of products versions.
2. Modify build jar task in Gradle to rename them ```version-local``` style.
3. Tag checkouts with version names.

Please let me know if I understood correctly and I will apply the above changes.

With best regards,

Nima

**Comment by msridhar** [comment]
Hi Nima, here is what I think we need to do.  We want a versioning / naming system to keep track of the versions of our tool @lazaroclapp is trying out, and also to ease his process of running the tools.  The first question is, what are all the artifacts required to run the autofixer?  I think they are:

* NullAway itself
* [Diagnoser](https://github.com/nimakarimipour/Diagnoser)
* [Injector](https://github.com/nimakarimipour/Injector)
* [NullAwayAutoFixer](https://github.com/nimakarimipour/NullAwayAutoFixer)

Is that it?  If we require any forks of any other open-source projects, those should be added to this list.

Once we have a complete list of relevant artifacts, we should follow steps like [these from the NullAway release instructions](https://github.com/uber/NullAway/blob/master/RELEASING.md#releasing) before we or @lazaroclapp do a full run of the tool.  Here is a modified version of the steps for our purposes:

 1. Change the version in `gradle.properties` to a non-SNAPSHOT version, instead using a -LOCAL suffix.  E.g., if the current version is `0.1.1-SNAPSHOT`, change it to `0.1.1-LOCAL`.
 2. `git commit -am "Prepare for release X.Y.Z-LOCAL."` (where X.Y.Z-LOCAL is the new version)
 3. `git tag -a vX.Y.Z-LOCAL -m "Version X.Y.Z-LOCAL"` (where X.Y.Z-LOCAL is the new version)
 4. Update the `gradle.properties` to the next SNAPSHOT version.  E.g., if the just-tagged version is `0.1.1-LOCAL`, change to `0.1.2-SNAPSHOT`.
 5. `git commit -am "Prepare next development version."`
 6. `git push && git push --tags`

With this scheme, to reproduce a previous run, we can check out the `vX.Y.Z-LOCAL` tag in all relevant repositories, publish to Maven Local, and re-do the run knowing we have the same versions as before.

A couple of notes:
* It would be good to use the same version number for all artifacts for simplicity.  For NullAway itself, we may need to use different version numbers.
* It may be worth keeping all the autofixer code in a single repository with multiple gradle modules, rather than having so many different repos.  This will make consistent versioning much easier.

@lazaroclapp please let us know if the above looks correct.

**Comment by lazaroclapp** [comment]
Those four projects look correct to me (and it's the complete list unless we fork javaparser again). The instructions are correct for the NullAway fork itself, but for the other projects there is no `gradle.properties` and the version numbers are all set on the `build.gradle` main build files directly. Other than that, the same workflow applies, I think.

As a note, I have been using `1.0.11-LOCAL` as my current version of NullAwayAutoFixer and Injector, so we might need to start with either `1.0.12-LOCAL` or, even better, `1.1.0-LOCAL` upstream for compatibility. For the NullAway fork, I am using `0.9.2.6-LOCAL`, where, afaik, `0.9.2` is the latest NullAway release (and the latest merged into the fork). For consistency, I'd request that the first upstream version here be `0.9.2.7-LOCAL` unless we release and merge a newer NullAway main version in between.

**Comment by nimakarimipour** [comment]
@msridhar @lazaroclapp Thank you very much for the instructions and clarifying what I have to do. I will use the version Lazaro suggested. I will close this issue once you approve the changes have been applied correctly.

Witth best regards

**Comment by msridhar** [comment]
@nimakarimipour is this done now?

**Comment by nimakarimipour** [comment]
> Hi @msridhar @lazaroclapp Yes I was doing a final test. Please let me know if everything is set up correctly.

**Comment by lazaroclapp** [comment]
So, `nullaway` looks fine to me, but keep in mind that the other ones should be `1.0.11-LOCAL` or `1.1.0-LOCAL`. They are currently set as `1.0-LOCAL`, which implies they predate the `1.0.10-LOCAL` releases I've already been using internally (technically that won't conflict with what I've run so far, because the build takes exact version numbers not "this version or later", but it still makes it hard to cut new releases and track future changes)

**Comment by msridhar** [comment]
@nimakarimipour could you do another set of release commits for the non-`nullaway` repos and use version number `1.1.0-LOCAL`?

**Comment by nimakarimipour** [comment]
@msridhar @lazaroclapp Yes sure, I will make another set of releases now.

**Comment by nimakarimipour** [comment]
> @msridhar @lazaroclapp Yes sure, I will make another set of releases now.

I deleted all wrong version tags locally and remotely. All ```non-nullaway``` projects start from ```1.1.0-LOCAL``` now. Also added ```CHANGELOG.md``` to all projects to keep track of versions. If that seems correct to you, please let me know and I will mark this issue as resolved.

**Comment by lazaroclapp** [comment]
All four repos look good to me now! Thanks!

**Comment by nimakarimipour** [comment]
> All four repos look good to me now! Thanks!

Thank you very much, I am closing this issue.
